security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /utilisateur/connection


    access_control:
        - { path: /utilisateur/connection, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /, roles: ROLE_UTILISATEUR }
